---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 10.0.1.5:5000/boshcpi/oracle-cpi-release
    tag: "latest"
    insecure_registries: [ "10.0.1.5:5000" ]
inputs:
  - name: bosh-cpi-src
  - name: version-semver
outputs:
  - name: candidate
run:
  path: bosh-cpi-src/ci/tasks/build-candidate.sh
