---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 10.0.1.5:5000/boshcpi/oracle-cpi-release
    tag: "latest"
    insecure_registries: [ "10.0.1.5:5000" ]
#    repository: pivotalgreenhouse/bosh-cli
#    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
run:
  path: bosh-cpi-src/ci/tasks/unit-tests.sh
